export default {
    headerBackgroundColor: '#f6f7f8',
    mainBackgroundColor: '#f6f7f8',
    colorDefaultBorder: '#6c757d',
    colorDefaultText: '#212529',
    colorDefaultActive: '#e2e6ea',
    colorDefault: '#e5e7eb',
    darkTextColor: '#0f172a',
    colorPrimaryText: '#ffffff',
    colorPrimary: '#007bff',
    colorPrimaryActive: '#0062cc',
    colorDanger: '#ff3333',
    colorInfo: '#e0eaf7',
    colorInfoActive: '#e1e7ef',
};